### ISSUE TITLE
3-1-2 my.cnfの設定

### ISSUE THREAD

**Issue by 1484** [virtualtech/openstack-liberty-docs#1]
3–1–2 MariaDBの設定を変更

my.cnfの編集でbind-addressがcontrollerノードのIPアドレスでは無くsqlノードと指定されています。今回MariaDBもcontrollerノードに入れるのですからIPアドレスと補足説明はcontrollerノードの情報へ修正が必要かと思います。

**Comment by ytooyama** [comment]
ありがとうございます。3-1-4に修正漏れがあったため、修正しました。また、前半の方にも修正漏れがあったため修正しました。
https://github.com/virtualtech/openstack-liberty-docs/tree/v1.0.3
diff: https://github.com/virtualtech/openstack-liberty-docs/commit/7134319e7c4255a9d8b65510784584fd9acfb29a

**Comment by ytooyama** [comment]
修正済みのため、クローズします。
