### ISSUE TITLE
8-2 mysql option

### ISSUE THREAD

**Issue by 1484** [virtualtech/openstack-liberty-docs#2]
8-2 データベースの確認のmysqlコマンドのオプションで、これまでの章では出てこなかったホスト指定(-h sql)がありますが不要かと思います。

**Comment by ytooyama** [comment]
ありがとうございます。該当の問題はv1.0まである誤記でした。diffが行方不明ですが、v1.0.1で修正しています。

**Comment by ytooyama** [comment]
修正済みのため、クローズします。
