### ISSUE TITLE
8–5 Neutronコンポーネントの設定を変更

### ISSUE THREAD

**Issue by masayuki1972** [virtualtech/openstack-liberty-docs#3]
以下、Controllerノードでの作業に関して、以下修正案の内容を実施するまで、「10–4 ネットワークの確認」において、パブリックネットワーク側ゲートウェイIPアドレス(10.0.0.200)にpingが飛びませんでした。
ご確認いただけますか。

・ML2プラグインの設定(P.63)
/etc/neutron/plugins/ml2/ml2_conf.ini
【1.0.1での記載】
　type_drivers = flat,vxlan ← 追記
【修正内容】
　type_drivers = flat,vlan,vxlan ← 追記

・Linuxブリッジエージェントの設定(P.64)
/etc/neutron/plugins/ml2/linuxbridge_agent.ini
【1.0.1での記載】
　記載なし(Compute側のみの記載)
【修正（追記）内容】
　[linux_bridge]
　physical_interface_mappings = public:eth0

**Comment by ytooyama** [comment]
Linuxブリッジエージェントの設定(P.64)の指摘につきましては1.0.1のドキュメントにも記載があります。1.0.1のPDFドキュメントが手元にないので、1.0.6の手順書のページで示すと64ページがコントローラ側、70ページがコンピュート側に対しての設定です。

**Comment by ytooyama** [comment]
前のご指摘については調べます。公式の手順では「type_drivers = flat,vlan,vxlan」が設定されていますね。

**Comment by masayuki1972** [comment]
Linuxブリッジエージェントの設定について、見落としていました。大変申し訳ありませんでした。

**Comment by ytooyama** [comment]
弊社の手順書ではNeutronネットワークでext-netをflat、Userネットワーク(demo-net)をvxlanで構築しているため、type_drivers = flat,vxlanと設定しています。VLANを使う場合はvlanを含めてください。
