### ISSUE TITLE
4-11 Keystoneの動作確認(apacheのlog確認)

### ISSUE THREAD

**Issue by 1484** [virtualtech/openstack-liberty-docs#4]
adminユーザとして管理トークン要求を入力して、その結果の確認としてapache2のkeystone_access.logでHTTP 200が帰ってくる事の確認をしています。

その下にログの抜粋が表示されていますが、トークン要求は http://controller:35357/v3 なのでログに表示されるPOSTは /v2.0 では無く、下記になるかと思います。また帰り値はトークン要求をしているので201のCreatedで正解でしょうか。

> "GET /v3 HTTP/1.1" 200 556 "-" "python-openstackclient"
> "POST /v3/auth/tokens HTTP/1.1" 201 1427 "-" "python-openstackclient"

**Comment by ytooyama** [comment]
ありがとうございます。v1.0.6-4で修正しました。
https://github.com/virtualtech/openstack-liberty-docs/blob/v1.0.6-4/OpenStackLiberty.md

**Comment by 1484** [comment]
遅くなり済みません、確認しました。ありがとうございます。
