### ISSUE TITLE
P12のサーバー

### ISSUE THREAD

**Issue by kujiraitakahiro** [virtualtech/openstack-liberty-docs#5]

**Comment by kujiraitakahiro** [comment]
台数が3台となっているが、２台。

**Comment by ytooyama** [comment]
最新版の1.0.6-5では次のように記述されています。
Open -> Close

1–5–1 インストール
2台のサーバーに対し、Ubuntu Serverをインストールします。要点は以下の通りです。

**Comment by ytooyama** [comment]
配布PDF版を更新しました。次のURLから更新版をダウンロード可能です。 http://enterprisecloud.jp/installguide-openstack/

**Comment by kujiraitakahiro** [comment]
ありがとうございます！
